### ISSUE TITLE
Production job failed to run

### ISSUE THREAD

**Issue by madasebrof** [quantum-elixir/quantum-core#312]
This is a slightly odd problem.

I consoled into our production box last night and connected to our production system using IEX. (e.g. using `IEX --remsh`) I must have failed to log out.

This AM, I got the following message:

```
Feb 27 06:00:00am web warn: Node :"console@192.168.0.18" is not running. Job :download could not be executed.
```

The job failed to run. When I check the scheduler, it looks fine:

```
iex(web-phoenix-52-1@192.168.0.18)11> Polo.Scheduler.find_job(:download)    
%Quantum.Job{name: :download, overlap: true, 
 run_strategy: %Quantum.RunStrategy.Random{nodes: :cluster},
 schedule: ~e[0 6 * * * *], state: :active,
 task: {Polo.Apex.Extract.Download, :run, ["apex"]},
 timezone: "America/New_York"}
```

Just trying to understand this behavior, or if as simple as "make sure there are no hanging connections to an Elixir app running Quantum or there will be problems!"

Or should I change the job to be `Quantum.RunStrategy.Local` so it always runs on the actual production box, not a remote node connecting to it?

**Comment by maennchen** [comment]
@madasebrof The strategy `%Quantum.RunStrategy.Random{nodes: :cluster}` will pick any connected node. If this node is hanging, you'll get this error.

**Comment by madasebrof** [comment]
Great, so change to `Quantum.RunStrategy.Local`???

**Comment by maennchen** [comment]
@madasebrof If you want all jobs to be executed on the node that started the scheduler, yes.

**Comment by madasebrof** [comment]
Awesome, thanks!!!!

**Comment by SofaKing18** [comment]
Had the same problem, what about to make Quantum.RunStrategy.Local default strategy?

**Comment by kaiatgithub** [comment]
@maennchen Please consider the suggestion of @SofaKing18. I ran into the same problem a while ago and suspect that many other developers will experience this. In my opinion, the most important function of this library is to reliably execute tasks. And the most reliable way is to execute tasks locally, without having to care about other applications connecting to the node. The ability to execute tasks remotely is a cool feature when scaling the application. Thank you for your hard work on this library!

**Comment by maennchen** [comment]
@kaiatgithub & @SofaKing18 

As long as you're not using clustering, the strategy is behaving exactly the same as the local strategy. Therefore for "normal" users, the strategy is exactly as expected.

As soon as you start using clustering though, you should also be concerned about cluster health. Since this is an advanced topic I think we can also expect users of that feature to make sure the cluster they built is actually stable.

So I don't think that the current default is a bad choice.

One thing I think that would make sense is to couple the default strategy with the `global` option.

Since this is a breaking change, this would have to wait for the next major release though.

**Comment by maennchen** [comment]
As soon as I have a little more time to dedicate to OS projects again, I'll tackle the problem about node health anyways. (also causes #334)

**Comment by kaiatgithub** [comment]
@maennchen Are there any disadvantages of making RunStrategy.Local the default? 

As you describe, many applications don't use multiple nodes. And then, to my understanding, the local strategy is exactly what is needed. And with this strategy, even when the developer decides to expand the app and connects it to another node, quantum will not fail and all jobs will be processed on the original node, as expected. If the developer then wants to distribute jobs to multiple nodes because they are consuming a lot of processing power, he/she can do that by changing the run strategy and carefully selecting which jobs should be executed on which node. Probably, some tasks still need to be executed locally because they need local resources, like database- or filesystem-access.

Currently, the random strategy is used as the default (correct?). In this situation, as soon as another node is connected, quantum will randomly distribute jobs to the local node and the new node. Each time the new node is selected by the random number generator, the job will not execute and quantum will log the error message reported by @madasebrof, because it cannot find the task supervisor on the new node. But the message wrongly states that the node itself is not running. This will confuse the developer and he/she will be frustrated. Further research, forum-posts or switch to another library are required to resolve the issue. This is an unnecessary weakness of quantum.

**Comment by maennchen** [comment]
@kaiatgithub Ow, now I see the problem. The strategy should select a place where the supervisor is running and not any node.
