### ISSUE TITLE
Erlang & Quantum Design Question

### ISSUE THREAD

**Issue by randysecrist** [quantum-elixir/quantum-core#333]
reference:  https://github.com/quantum-elixir/quantum-core/issues/264

So fundamental erlang question here ...  using global registration ..

How is it quantum restarts jobs for BEAM nodes which die (using control-c) on other connected nodes?

Supervisors don't typically monitor pids on other nodes.  So ... where is the manual Process.monitor bit done at?

**Comment by maennchen** [comment]
@randysecrist If you monitor a pid on another node and this node goes down, you'll get this message:

```
{:DOWN, #Reference<0.3175945100.3353870340.142203>, :process, #PID<14627.118.0>, :noconnection}
```

I was however not aware that the `Supervisor` does not handle that message.

I wanted to prepare you a little test repo and just found that this doesn't work as I expected.

I'll open a bug and will inform you with the details as soon as it works.

Since this question is not really an issue on quantum, I'm closing it.
