### ISSUE TITLE
failed to start child Quantum.ClusterTaskSupervisorRegistry

### ISSUE THREAD

**Issue by chandankumar4** [quantum-elixir/quantum-core#377]
I'm facing this issue when i starrted my application. can anyone help with this
```
[info] Running testApi.Endpoint with Cowboy using http://0.0.0.0:4000
[info] Application openebsci_dashnoard_api exited: testApi.start(:normal, []) returned an error: shutdown: failed to start child: testApi.Scheduler
    ** (EXIT) shutdown: failed to start child: Quantum.ClusterTaskSupervisorRegistry
        ** (EXIT) exited in: :gen_statem.call(Swarm.Tracker, {:track, :"Elixir.#Reference<0.2248818178.2542796803.104653>", #PID<0.410.0>, %{}}, :infinity)
            ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
** (Mix) Could not start application openebsci_dashnoard_api: testApi.start(:normal, []) returned an error: shutdown: failed to start child: testApi.Scheduler
    ** (EXIT) shutdown: failed to start child: Quantum.ClusterTaskSupervisorRegistry
        ** (EXIT) exited in: :gen_statem.call(Swarm.Tracker, {:track, :"Elixir.#Reference<0.2248818178.2542796803.104653>", #PID<0.410.0>, %{}}, :infinity)
            ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
```

Phoenix v1.3.4
Erlang/OTP 21 [erts-10.0.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Eshell V10.0.5  (abort with ^G)
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
node version:- v8.11.4

**Comment by maennchen** [comment]
@chandankumar4 It seems `:swarm` is not running. Did you override the `applications` in you `mix.exs` file?

**Comment by chandankumar4** [comment]
yes! i override it

**Comment by maennchen** [comment]
If you're using Elixir 1.3 or newer, do not do that except when you got a really good reason. Mix automatically will detect all applications you need and start them. If you override it, this will not work except when done with much care.

Most likely you can delete that `application` key and its contents and the application will work.

To explain more properly of what is going on, see https://www.amberbit.com/blog/2017/9/22/elixir-applications-vs-extra_applications-guide/

I'm closing this issue since it is not a problem of this library. Do not hesitate to reply though.
