### ISSUE TITLE
Tuples for job names?

### ISSUE THREAD

**Issue by theangryangel** [quantum-elixir/quantum-core#379]
If I put together a quick patch to allow job names to be set as tuples, not just atoms, would that be something you'd be happy to pull, in theory?

I'm looking at building a system which would result in effectively user defined jobs that I'd need to be able to delete at a later date. If I rely on atom names I'll run the risk of atom exhaustion eventually, but if I use references I have no effect way to store them in my DB and then find them at a later date it seems.

I've done a really quick PoC and it seems to behave OK. 

Or am I barking up the wrong tree and is there a better way?

**Comment by maennchen** [comment]
The current application allows for atoms & references as job names. If you have a grander scheme on how to manage jobs I'd recommend you to use references and then keep some kind of registry.

We allowed for more job name types in the v1 branch, but this was removed in favor of a cleaner interface.

If we were to do the proposed change, this could only be done in v3 since this would pose a breaking change for the storage adapters. v3 is still a longer way to go currently.

I think your problem can be solved using references as names, do you agree with that?

**Comment by theangryangel** [comment]
I was having issues storing references outside of elixir (I.e. Postgres) and then reloading them, but perhaps I’ve missed something.

Thanks for the advice and fantastic library ❤️

**Comment by maennchen** [comment]
@theangryangel There's a way to serialize / unserialize references:

* `:erlang.ref_to_list/1` - converts a reference to a charlist
* `:erlang.list_to_ref/1` - converts a charlist back to a reference

http://erlang.org/doc/man/erlang.html

**Comment by maennchen** [comment]
@theangryangel Do not hesitate to ask again if you're having problems setting things up with this approach.

**Comment by LostKobrakai** [comment]
I'm not really comfortable with having my own registry with names -> refs, as I don't feel like I know enough about quantums internals to be sure I don't get into race conditions between my registry and quantum and even how to do proper cleanup in case of errors in the first place. 
If adapters are meant to have a simpler interface than in v1 and a registry is the proposed solution, then I'm wondering why quantum shouldn't be able to do the registry + name conversion leaving the adapter interface the same and enabling to widen the interface for quantum users.
