### ISSUE TITLE
Docs: Must start swarm application

### ISSUE THREAD

**Issue by DavidMikeSimon** [quantum-elixir/quantum-core#387]
After following the setup instructions in the README, I got this error when attempting to start my app:

```
** (Mix) Could not start application undertoe: Undertoe.start(:normal, []) returned an error: shutdown: failed to start child: Undertoe.Scheduler
    ** (EXIT) shutdown: failed to start child: Quantum.ClusterTaskSupervisorRegistry
        ** (EXIT) exited in: :gen_statem.call(Swarm.Tracker, {:track, :"Elixir.#Reference<0.3203166617.2649751553.187640>", #PID<0.3374.0>, %{}}, :infinity)
            ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
```

To fix this, I just needed to add `:swarm` to my applications list in `mix.exs`.

This may simply be something missing from the docs, however I'm not familiar enough with Elixir to be sure that I'm doing the right thing to resolve it.

**Comment by maennchen** [comment]
@DavidMikeSimon Since Elixir 1.3, the applications are automatically started depending on the installed dependencies. If the applications configuration is untouched (which is recommended) and only extra_applications are configured this works fine.

If you decide to overwrite this in your project, you‘ll have to figure this out yourself I guess.

Quantum will always require all deoendencies to be started before quantum itself. If the applications are managed manually every patch release could possibly be a breaking change.

This article explains the topis in some more detail:

https://www.amberbit.com/blog/2017/9/22/elixir-applications-vs-extra_applications-guide/

**Comment by DavidMikeSimon** [comment]
@maennchen Thank you, that makes things a lot clearer for me! 😄
