### ISSUE TITLE
Problem: Would like :info that Quantum is running (not :debug)

### ISSUE THREAD

**Issue by sensiblearts** [quantum-elixir/quantum-core#447]
I request that you change the prority level of these messages from :debug to :info:
```
14:16:12.124 [info] [Pow.Store.Backend.MnesiaCache] Mnesia cluster initiated on :...
14:16:12.125 [debug] Elixir.Quantum.JobBroadcaster] Loading Initial Jobs from Config
```
And perhaps this too:
```
14:16:12.127 [debug] Elixir.Quantum.ExecutionBroadcaster] Adding job #Reference..
```

**Comment by maennchen** [comment]
Can you supply a reason why you want this change?

**Comment by sensiblearts** [comment]
@maennchen Thank you for the prompt reply.

I am trying to figure out why my job runs fine every 5 minutes, but failed to run when I changed to "@daily".

At first I thought Quantum was not running because there was nothing in the logs. So I tried adding it to :extra_applications.  I.e., wasting time.

I just noticed that Pow logs its startup as :info, so I thought that might be common practice.

If there is a more standard way to confirm that all apps are started, please let me know.

Thanks.

**Comment by maennchen** [comment]
@sensiblearts I think this might be the wrong approach.

Generally saying you are sure that your application only starts after all dependent applications have been started.

In the case of quantum, this does not apply since the `Scheduler` is started by your application and not `quantum` itself.

If you added the `Scheduler` to your `Application` / `Supervisor` as stated in the installation docs, those would warn you if the `Scheduler` could not be started.

I think it would be very bad if every application would log that it is starting. in a big project you would have a vast amount of messages that are basically only confirming that OTP is working as intended.

Also, if you're already spending time debugging why something works / doesn't, I think it is also reasonable that people enable `debug` logs to verify what's happening.

PS: Logs can be manipulated application / Module specific:

* https://hexdocs.pm/logger/Logger.html#module-application-configuration
* https://hexdocs.pm/flex_logger/FlexLogger.html

**Comment by sensiblearts** [comment]
Thank you! That sounds good.
