### ISSUE TITLE
Logging messages could be replaced by telemetry events

### ISSUE THREAD

**Issue by isaacsanders** [quantum-elixir/quantum-core#461]
The current logging messages could be a source of useful metrics data. This approach was taken for the Redix library to improve the developer experience related to logging: https://github.com/whatyouhide/redix/issues/127

**Comment by maennchen** [comment]
@isaacsanders 
I believe that the logging is very helpful purposes. It’s also not intrusive since it can be toggeled on / off in the config.

Is there any telemetry events on top of the current ones that you are missing at the moment?

**Comment by isaacsanders** [comment]
Are all the current Logging events transmitted as telemetry events? Logging can be added as a telemetry event handler, so we can remove all logging from the main execution.

**Comment by maennchen** [comment]
@isaacsanders I would not add a telemetry event to all the places that currently log a message since some of those I would consider internal and not interesting to a user of the library.

(If we refactor some code, they could easily change in the future without introducing changes into the userland.)

If we would replace all logger messages we would therefore need „internal“ telemetry events, but that seems to complicated to just attach a logger again for debugging.

I‘m all in to expose all relevant events to the user and if you think there’s some missing, we can expose those events for sure. I don’t think that I agree that it completely replaces (opt in) logging though.
